Chương 2 : MA TRẬN VÀ HỆ PHƯƠNG TRÌNH TUYẾN
TÍNH 

Câu 1 : Dẫn nhập - một số hàm về xử lý vector với Python $\vec{v} = (a, b) \Rightarrow k\vec{v} = (ka, kb)$


In [1]:
def scale(a,v) :
    return [a*vi for vi in v]

In [2]:
v = [3,5,7]
scale(10, v)

[30, 50, 70]

#Tổng hai vectorvector

In [3]:
def sumvector(v, w):
    return [vi + wi for (vi, wi) in zip(v, w)]

In [4]:
w = [2, 4, 6]
sumvector(v, w)

[5, 9, 13]

#Tích vô hướng 

In [5]:
def dotvector(v, w):
    return sum([vi * wi for (vi, wi) in zip(v, w)])
dotvector(v, w)

68

#Chiều dài vector (tổng bình phương)

In [6]:
def lenvector(v):
    return dotvector(v, v)

lenvector(w)

56

Câu 2 : Phân loại tuyến tính với NumPy


In [23]:
import numpy as np
scores = np.array([-1,1, 2, -3, 5, -4])
scores >= 0 

array([False,  True,  True, False,  True, False])

In [24]:
scores < 0

array([ True, False, False,  True, False,  True])

In [46]:
np.select([scores >= 0, scores < 0], ['số dương', 'số âm'], default='không xác định')


array(['số âm', 'số dương', 'số dương', 'số âm', 'số dương', 'số âm'],
      dtype='<U14')

#Phân loại 3 loại : dương , âm bằng 0

In [82]:
scores=np.array([-1,1,2,0,-3,5,0,-4])
np.select([scores>0,scores==0,scores<0],['so duong','so 0','so am'],default='không xác định')

array(['so am', 'so duong', 'so duong', 'so 0', 'so am', 'so duong',
       'so 0', 'so am'], dtype='<U14')

Cau 3 : xử lý ma trận cơ bản

In [ ]:
1#
import numpy as np 
from scipy import linalg, sparse

Dap an cua D :[[3 4]
 [5 6]]
Dap an C : [[0.90011772 0.79320647 0.77811215 0.62198641 0.86326557 0.22173539
  0.15209681]
 [0.77615414 0.95884334 0.50432456 0.9428202  0.16251273 0.6898361
  0.69228816]
 [0.48184792 0.95550991 0.82831731 0.36010439 0.91034093 0.24739252
  0.00238715]
 [0.37575136 0.34662171 0.49524249 0.73776258 0.38410807 0.99925712
  0.6398963 ]
 [0.9233242  0.90577441 0.262043   0.97399659 0.70515116 0.95470709
  0.39844052]]
Dap an cuar A : [[0.65225789 0.54904001]
 [0.27404427 0.73353284]]
Dap an cua b : [[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
Dap an cua D : [[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [106]:
#2
D = np.array ([ [3,4], [5,6] ])
print (f'Dap an cua D :{D}') 


Dap an cua D :[[3 4]
 [5 6]]


In [105]:
#3
C= np.array(np.random.random((5,7)))
print (f'Dap an C : {C}') 

Dap an C : [[0.79170868 0.05050038 0.10184954 0.88363368 0.0530631  0.84217
  0.07093626]
 [0.36714617 0.99224741 0.16151226 0.67941869 0.73256035 0.11042878
  0.8865753 ]
 [0.22894833 0.40551591 0.64414306 0.96212874 0.70433067 0.35597163
  0.15721848]
 [0.2669282  0.93589426 0.14963328 0.0830995  0.24035609 0.48973198
  0.94498435]
 [0.39566148 0.44091915 0.25298845 0.81664978 0.19115682 0.96075767
  0.44415557]]


In [104]:
#4
A= np.array(np.random.random((2,2)))
print(f'Dap an cuar A : {A}')

Dap an cuar A : [[0.8065665  0.52350408]
 [0.46667004 0.41145656]]


In [103]:
#5
b = np.array([(1+5j, 2j, 3j),(4, 5,6)])
B = np.asmatrix(b) 
print (f'Dap an cua b : {b}')
print(f'Dap an cua D : {B}')

Dap an cua b : [[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]
Dap an cua D : [[1.+5.j 0.+2.j 0.+3.j]
 [4.+0.j 5.+0.j 6.+0.j]]


In [102]:
#6
A.T

array([[0.65225789, 0.27404427],
       [0.54904001, 0.73353284]])

In [101]:
#7
linalg.inv(A)

array([[ 2.23643986, -1.67394682],
       [-0.83552298,  1.98864381]])

In [100]:
#8
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_lower = np.tril(M) 
print(M_lower)

[[-1  0  0]
 [ 0 -2  0]
 [ 1  5 -2]]


In [99]:
#9 
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
M_upper = np.triu(M)
print(M_upper) 

[[-1  3  2]
 [ 0 -2  1]
 [ 0  0 -2]]


In [108]:
#10 
M = np.array([[-1,3,2],[0,-2,1],[1,5,-2]])
v_diag = np.diag(M) #vector đường chéo
print (v_diag)
M_diag = np.diag(v_diag)
print (M_diag) 


[-1 -2 -2]
[[-1  0  0]
 [ 0 -2  0]
 [ 0  0 -2]]


Cau 3.2 :

In [109]:
import numpy as np
A = np.reshape(np.arange(36.0), (6,6))
print (A)

[[ 0.  1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10. 11.]
 [12. 13. 14. 15. 16. 17.]
 [18. 19. 20. 21. 22. 23.]
 [24. 25. 26. 27. 28. 29.]
 [30. 31. 32. 33. 34. 35.]]


In [110]:
I6 = np.identity(6)
print (I6)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [111]:
print(A.size)

36


In [112]:
print(np.matrix.diagonal(A))

[ 0.  7. 14. 21. 28. 35.]


In [113]:
A = A + I6
print (A)

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


Tính tích (nhân) ma trận với vector (là dạng ma trận đặc biệt): 

In [114]:
vecB = np.array([1., 2., 3., 4., 5., 6.])
C = A.dot(vecB)
print (C)

[ 71. 198. 325. 452. 579. 706.]


Khai báo ma trận D 2x62x6

In [115]:
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
print (D)

[[1. 2. 3. 4. 5. 6.]
 [1. 0. 1. 0. 1. 0.]]


Tính tích ma trận A và D 


In [ ]:
D = np.array([[1., 2., 3., 4., 5., 6.], [1., 0., 1., 0., 1., 0.]])
E = A.dot(D)
print (E)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 6)

Xây dựng ma trận F kích thước 6 x2 : 

In [119]:
F = np.array([[1., 1.], [2., 0.], [3., 1.], [4., 0], [5., 1], [6., 0.]])
G = A.dot(F)
print (F)

[[1. 1.]
 [2. 0.]
 [3. 1.]
 [4. 0.]
 [5. 1.]
 [6. 0.]]


In [120]:
print (G)

[[ 71.   7.]
 [198.  24.]
 [325.  43.]
 [452.  60.]
 [579.  79.]
 [706.  96.]]


Tính ma trận nghịch đảo : 


In [121]:
print(np.linalg.inv(A))

[[ 0.37022901 -0.45610687 -0.28244275 -0.10877863  0.0648855   0.23854962]
 [-0.44656489  0.65839695 -0.23664122 -0.13167939 -0.02671756  0.07824427]
 [-0.26335878 -0.22709924  0.80916031 -0.15458015 -0.11832061 -0.08206107]
 [-0.08015267 -0.11259542 -0.14503817  0.82251908 -0.20992366 -0.24236641]
 [ 0.10305344  0.0019084  -0.09923664 -0.20038168  0.69847328 -0.40267176]
 [ 0.28625954  0.11641221 -0.05343511 -0.22328244 -0.39312977  0.4370229 ]]


In [122]:
print(np.linalg.inv(np.linalg.inv(A)))

[[ 1.  1.  2.  3.  4.  5.]
 [ 6.  8.  8.  9. 10. 11.]
 [12. 13. 15. 15. 16. 17.]
 [18. 19. 20. 22. 22. 23.]
 [24. 25. 26. 27. 29. 29.]
 [30. 31. 32. 33. 34. 36.]]


Câu 4 : Phép nhân ma trận và biến đổ

In [60]:
import numpy as np
A = np.array( [ [1,1], [1,0] ] )
b = np.array([1, 0])
n = 10 
for i in range(n):
    b = A.dot(b)
    print(b) 


[1 1]
[2 1]
[3 2]
[5 3]
[8 5]
[13  8]
[21 13]
[34 21]
[55 34]
[89 55]


Câu 5 : Cơ bản về hệ phương trình tuyến tính và ứng dụng minh họa 

In [61]:
import sympy as sp
from sympy import Symbol
x1 = Symbol('x1')
x2 = Symbol('x2')
x3 = Symbol('x3')
x4 = Symbol('x4')
from sympy import solve
pt1 = x4+610-450-x1
pt2 = x1+400-x2-640
pt3 = x2+600-x3
pt4 = x3-x4-520
nghiem = sp.solve((pt1, pt2, pt3, pt4))
nghiem 

{x1: x4 + 160, x2: x4 - 80, x3: x4 + 520}

Bài tập : sinh viên thử bằng phương pháp nhân ma trận :

In [76]:
import numpy as np
A = np.array([[-1,0,0,1],[1,-1,0,0],[0,1,-1,0],[0,0,1,-1]])
#Và tính ma trận nghịch đảo:
A_nghichdao = np.linalg.det(A)
print(A_nghichdao )

0.0


Bài tập chương 2 

Câu 1 : Hãy sử dụng numpy để giải các chương trình sau :

Vấn đề 1 : Tìm điểm giao điểm giữa hai đường thẳng trong R^2 

In [74]:
import numpy as np
A = np.array([[0, 1], [2, 3]])
b = np.array([-2, 6])
solution_bai1 = np.linalg.solve(A, b)
print("Điểm giao trong R^2:", solution_bai1)

Điểm giao trong R^2: [ 6. -2.]


Vấn đề 2 (PROBLEM 2):Tìm giao điểm giữa ba mặt phẳng trong R^33

In [77]:
A = np.array([[1, -1, 0], [2, -1, 0], [1, 1, 1]])
b = np.array([-2, -3, 6])
solution_bai2 = np.linalg.solve(A, b)
print("Điểm giao trong R^3:", solution_bai2)

Điểm giao trong R^3: [-1.  1.  6.]


Vấn đề 3 (Problem 3) : Tìm các hệ số đa thức để đa thức thỏa các nghiệmnghiệm

In [78]:
A = np.array([[1**2, 1, 1], [2**2, 2, 1], [3**2, 3, 1]])
b = np.array([4, 3, 4])
coefficients = np.linalg.solve(A, b)
a, b_coeff, c = coefficients
print("Hệ số đa thức bậc 2: a =", a, ", b =", b_coeff, ", c =", c)

Hệ số đa thức bậc 2: a = 1.0000000000000004 , b = -4.000000000000001 , c = 7.000000000000001


Vấn đề 4 (problem 4) : Tìm các hệ đa thức khi phân rã để tính tích phânphân

In [79]:
from scipy.integrate import quad

def integrand(x):
    return x * (x - 3) / (x**2 + 2)

result, error = quad(integrand, 1, 2)
print("Kết quả tích phân:", result)

Kết quả tích phân: -0.5203227371848946


Câu 2 : Hãy viết các câu lệnh của symoy để giải các phương trình ở Câu 1 


In [80]:
import numpy as np
from scipy.special import comb
from scipy.integrate import quad
import sympy as sp

x, y = sp.symbols('x y')
equ1 = sp.Eq(x, y)
equ2 = sp.Eq(2*x + 3*y, 6)
solution = sp.solve([equ1, equ2], (x, y))
print("Nghiệm hệ phương trình trong R^2:", solution)

Nghiệm hệ phương trình trong R^2: {x: 6/5, y: 6/5}


 **Câu 3:** Tính lũy thừa bậc $k$ của ma trận 
$$
F_k = \begin{pmatrix} 1 & 1 \\ 1 & 0 \end{pmatrix}^k
$$
và chứng minh ma trận $F_k$ chứa 3 phần tử của $Fibo_{k+1}, Fibo_k$ và $Fibo_{k-1}$ của dãy Fibonacci (bắt đầu bằng 0 từ phần tử 0).


In [81]:
import numpy as np

def fibonacci(n):
    fib = [0, 1]
    for i in range(2, n):
        fib.append(fib[-1] + fib[-2])
    return fib
k = 3  
F_k = np.array([[1, 1], [1, 0]])  
F_k_power = np.linalg.matrix_power(F_k, k)
print(f"Ma trận F_{k}^{{{k}}}:\n{F_k_power}")
fib_sequence = fibonacci(k+1)  
print("Các phần tử của dãy Fibonacci bắt đầu từ 0 đến index", k+1, ":", fib_sequence)
sum_fib = sum(fib_sequence)
print("Tổng các phần tử của dãy Fibonacci đến index", k+1, ":", sum_fib)

Ma trận F_3^{3}:
[[3 2]
 [2 1]]
Các phần tử của dãy Fibonacci bắt đầu từ 0 đến index 4 : [0, 1, 1, 2]
Tổng các phần tử của dãy Fibonacci đến index 4 : 4
