In [20]:
#1 Định thức và các tính chất
import numpy as np

n = 4
X = np.array(range(1, n + 1))

def sgn_by_def(sigma):
    ket_qua = 1.0
    for i in range(len(X) - 1):
        for j in range(i + 1, len(X)):
            ket_qua *= ((X[i] - X[j]) / (sigma[i] - sigma[j]))
    return int(ket_qua)
sigma1 = np.array([2, 1, 3, 4])
print("sgn([2,1,3,4]) =", sgn_by_def(sigma1))
sigma2 = np.array([1, 2, 3, 4])
print("sgn([1,2,3,4]) =", sgn_by_def(sigma2))
sigma3 = np.array([4, 3, 2, 1])
print("sgn([4,3,2,1]) =", sgn_by_def(sigma3))



sgn([2,1,3,4]) = -1
sgn([1,2,3,4]) = 1
sgn([4,3,2,1]) = 1


In [6]:
# 1 Định thức và các tính chất
import numpy as np
from itertools import permutations

def sgn_by_def(sigma):
    n = len(sigma)
    inv_count = 0
    for i in range(n):
        for j in range(i + 1, n):
            if sigma[i] > sigma[j]:
                inv_count += 1
    return (-1) ** inv_count
def phatsinh_dinhthuc(n):
    X = []
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = ""
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize((n,))
        product = ""
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product += "a" + str(i) + str(sn.index(i)+1)
        dau = sgn_by_def(sigma)
        if dau != 1:
            product = " - " + product
        else:
            product = " + " + product
        dinhthuc += product
    return dinhthuc
def tinhtoan_dinhthuc(A):
    import math
    X = []
    n = int(math.sqrt(A.size))  # tính kích thước của ma trận
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = 0
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize((n,))
        product = 1
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product *= A[i-1][sn.index(i)]
        dau = sgn_by_def(sigma)
        if dau != 1:
            product *= -1
        dinhthuc += product
    return dinhthuc
A = np.array([[3, 5, -8],
              [4, 12, -1],
              [2, 5, 3]])

print("Biểu thức định thức n=2:", phatsinh_dinhthuc(2))
print("Biểu thức định thức n=3:", phatsinh_dinhthuc(3))
print("Giá trị định thức:", tinhtoan_dinhthuc(A))


Biểu thức định thức n=2:  + a11a22 - a12a21
Biểu thức định thức n=3:  + a11a22a33 - a11a23a32 - a12a21a33 + a13a21a32 + a12a23a31 - a13a22a31
Giá trị định thức: 85


In [7]:
# 2 Định thức và ma trận khả nghịch
#Hệ hai phương trình tuyến tính bậc 1:
import numpy as np
from scipy import linalg
A = np.array([[4, -2], [3, -5]])
A1 = np.array([[10, -2], [11, -5]])
A2 = np.array([[4, 10], [3, 11]])
# Tính định thức
detA = linalg.det(A)
detA1 = linalg.det(A1)
detA2 = linalg.det(A2)
print("Các định thức:")
print("det(A) =", detA)
print("det(A1) =", detA1)
print("det(A2) =", detA2)
# Áp dụng quy tắc Cramer
if detA != 0:
    x1 = detA1 / detA
    x2 = detA2 / detA
    print("Hai nghiệm của phương trình là:", x1, x2)
else:
    print("Hệ phương trình vô nghiệm hoặc vô số nghiệm.")

Các định thức:
det(A) = -14.0
det(A1) = -28.0
det(A2) = 14.000000000000004
Hai nghiệm của phương trình là: 2.0 -1.0000000000000002


In [15]:
#Hệ ba phương trình tuyến tính bậc 1:
import numpy as np
from itertools import permutations
import math
# Hàm tính dấu của phép hoán vị sigma
def sgn_by_def(sigma):
    n = len(sigma)
    count = 0
    for i in range(n):
        for j in range(i+1, n):
            if sigma[i] > sigma[j]:
                count += 1
    return -1 if count % 2 else 1
# Hàm tính định thức theo định nghĩa
def tinhtoan_dinhthuc(A):
    X = []
    n = int(math.sqrt(A.size))
    for i in range(1, n+1):
        X.append(i)
    Sn = list(permutations(X))
    dinhthuc = 0
    for sn in Sn:
        sigma = np.array([1])
        sigma.resize([n])
        product = 1
        for i in range(1, n+1):
            sigma[sn.index(i)] = i
            product *= A[i-1][sn.index(i)]
        dau = sgn_by_def(sigma)
        if dau != 1:
            product *= -1
        dinhthuc += product
    return dinhthuc
# Khai báo các ma trận
A = np.array([[-1, 2, -3],
              [ 2, -2, 1],
              [ 3, -4, 4]])

AX = np.array([[1, 2, -3],
               [3, -2, 1],
               [2, -4, 4]])

AY = np.array([[-1, 1, -3],
               [ 2, 3, 1],
               [ 3, 2, 4]])

AZ = np.array([[-1, 2, 1],
               [ 2, -2, 3],
               [ 3, -4, 2]])

# Tính các định thức
detA = tinhtoan_dinhthuc(A)
detX = tinhtoan_dinhthuc(AX)
detY = tinhtoan_dinhthuc(AY)
detZ = tinhtoan_dinhthuc(AZ)

# Giải hệ phương trình
if detA != 0:
    x, y, z = detX/detA, detY/detA, detZ/detA
    print("Nghiệm của hệ phương trình là:")
    print("x =", x, "y =", y, "z =", z)
else:
    print("Hệ phương trình vô nghiệm hoặc vô số nghiệm.")


Hệ phương trình vô nghiệm hoặc vô số nghiệm.


In [16]:
#Bai tap chuong
#bai 1
import numpy as np
# Hàm lấy ma trận con khi loại bỏ dòng i và cột j
def get_minor(matrix, i, j):
    minor = np.delete(matrix, i, axis=0)  # Xóa dòng i
    minor = np.delete(minor, j, axis=1)   # Xóa cột j
    return minor
def cofactor_matrix(A):
    n = A.shape[0]
    C = np.zeros((n, n))
    for i in range(n):
        for j in range(n):
            minor = get_minor(A, i, j)
            C[i][j] = ((-1) ** (i + j)) * np.linalg.det(minor)
    return C
def adjoint_matrix(A):
    C = cofactor_matrix(A)
    return C.T
A = np.array([[2, -1, 0],
              [1, 3, 4],
              [0, 2, 1]])

print("Ma trận A:")
print(A)
C = cofactor_matrix(A)
print("\nMa trận hệ số phụ (cofactor matrix):")
print(C)
Adj = adjoint_matrix(A)
print("\nMa trận liên hợp (adjoint matrix):")
print(Adj)

Ma trận A:
[[ 2 -1  0]
 [ 1  3  4]
 [ 0  2  1]]

Ma trận hệ số phụ (cofactor matrix):
[[-5. -1.  2.]
 [ 1.  2. -4.]
 [-4. -8.  7.]]

Ma trận liên hợp (adjoint matrix):
[[-5.  1. -4.]
 [-1.  2. -8.]
 [ 2. -4.  7.]]


In [19]:
#Bai 2
import sympy as sp
x, y = sp.symbols('x y')
# Nhập 3 điểm trên mặt phẳng
x1, y1 = 1, 1
x2, y2 = 2, 4
x3, y3 = 5, 3
# Tạo ma trận định thức
circle_matrix = sp.Matrix([
    [x**2 + y**2, x, y, 1],
    [x1**2 + y1**2, x1, y1, 1],
    [x2**2 + y2**2, x2, y2, 1],
    [x3**2 + y3**2, x3, y3, 1]
])

equation = sp.simplify(circle_matrix.det())

print("Phương trình đường tròn đi qua 3 điểm là:")
sp.pprint(sp.Eq(equation, 0))


Phương trình đường tròn đi qua 3 điểm là:
      2              2                
- 10⋅x  + 60⋅x - 10⋅y  + 40⋅y - 80 = 0
