In [ ]:
#bai 1
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("Tích vô hướng (vector 1 chiều):")
print("np.inner(a, b):", np.inner(a, b))
print("np.dot(a, b):", np.dot(a, b))
print()
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Ma trận 2 chiều:")
print("A =\n", A)
print("B =\n", B)
print()
print("np.inner(A, B):")
print(np.inner(A, B))
print()
print("np.dot(A, B):")
print(np.dot(A, B))

Tích vô hướng (vector 1 chiều):
np.inner(a, b): 32
np.dot(a, b): 32

Ma trận 2 chiều:
A =
 [[1 2]
 [3 4]]
B =
 [[5 6]
 [7 8]]

np.inner(A, B):
[[17 23]
 [39 53]]

np.dot(A, B):
[[19 22]
 [43 50]]


In [ ]:
#bai 2
import numpy as np
m = 10
v1 = np.array([5, -4, 3])
v2 = np.array([4, 3, -2])
v3 = np.array([-4, -3, -1])
v4 = np.array([-9, 8, 6])
mi = np.array([2, 5, 2, 1])
M = np.array([v1, v2, v3, v4])
MT = M.transpose()
print("MT =")
print(MT)
v = (1.0 / m) * MT.dot(mi)
print("v =")
print(v)

MT =
[[ 5  4 -4 -9]
 [-4  3 -3  8]
 [ 3 -2 -1  6]]
v =
[1.3 0.9 0. ]


In [ ]:
#bai 3
import numpy as np
A = np.array([[0.998, 0.136],
              [0.002, 0.864]])
v0 = np.array([0.95, 0.05])
A_100 = np.linalg.matrix_power(A, 100)
v100 = A_100 @ v0
print("Trạng thái sau 100 tuần:")
print(v100)

Trạng thái sau 100 tuần:
[0.98550723 0.01449277]


In [ ]:
#bai 4
import numpy as np
A = np.array([[1, 6],
              [5, 2]])
u = np.array([6, -5])
Au = A @ u
print("A @ u =", Au)
minus4u = -4 * u
print("-4 * u =", minus4u)
print("A @ u == -4 * u ?", np.allclose(Au, minus4u))


A @ u = [-24  20]
-4 * u = [-24  20]
A @ u == -4 * u ? True


In [ ]:
#bai 5
import numpy as np
from numpy import linalg as LA
A = np.array([[2, 3],
              [3, -6]])
D = np.array([[-7, 0],
              [0, 3]])
P = np.array([[-1.0/3, 3],
              [1,      1]])
P1 = LA.inv(P)
print("P^(-1) =")
print(P1)

P^(-1) =
[[-0.3  0.9]
 [ 0.3  0.1]]


In [ ]:
#bai tap chuong
#bai 1
import numpy as np
import math
a = np.array([1, 2, 3])
mag_a = np.sqrt(a.dot(a))         # a
mag_b = np.sqrt(a @ a)            # b
mag_c = np.sqrt(np.inner(a, a))   # c
mag_d = (lambda x: math.sqrt(sum(i**2 for i in x)))(a)  # d
print(mag_a, mag_b, mag_c, mag_d)  # All should print sqrt(14) ≈ 3.7417


3.7416573867739413 3.7416573867739413 3.7416573867739413 3.7416573867739413


In [ ]:
#bai tap chuong
#bai 2
import numpy as np
from numpy import dot, linalg
from math import acos, degrees
# Khai báo 2 vector
u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
# a. Tính khoảng cách ||u - v||
distance = linalg.norm(u - v)
print("a. Khoảng cách ||u - v|| =", distance)
# b. Tính góc theta giữa u và v
dot_uv = dot(u, v)
norm_u = linalg.norm(u)
norm_v = linalg.norm(v)
cos_theta = dot_uv / (norm_u * norm_v)
theta_rad = acos(cos_theta)
theta_deg = degrees(theta_rad)
print("b. Góc giữa u và v (radian):", theta_rad)
print("   Góc giữa u và v (degree):", theta_deg)
# c. Phép chiếu trực giao của u lên v
projection_scalar = dot(u, v) / dot(v, v)
projection = projection_scalar * v
print("c. Phép chiếu u lên v:", projection)

a. Khoảng cách ||u - v|| = 5.196152422706632
b. Góc giữa u và v (radian): 0.2257261285527342
   Góc giữa u và v (degree): 12.933154491899135
c. Phép chiếu u lên v: [1.66233766 2.07792208 2.49350649]
