Chương 3 : Ma trận và hệ phương trình tuyến tính

1.1 Một số phép xử lý ma trận của NumPy và Scipy


    Khởi tạo ma trận:
Khai báo thêm thư viện scipylinalg và một số các vector khởi tạo:

In [1]:
from scipy import linalg
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
b = np.array([(1+9j, 2j, 3j), (4j, 5j, 6j)]) # số phức
c = np.array([[ (0.5, 1.5, 10), (3,2,1) ] , [(6,5,4), (7,8,9)]]) # ma trận số thực 
print ( a,b,c)

[1 2 3] [[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]] [[[ 0.5  1.5 10. ]
  [ 3.   2.   1. ]]

 [[ 6.   5.   4. ]
  [ 7.   8.   9. ]]]


Các kiểu khai báo và khởi tạo ma trận: 

In [13]:
A = np.matrix(np.random.random( (2,2) ) )
B = np.asmatrix(b) # Chuyển b thành dạng ma trận
C = np.asmatrix(np.random.random( (10,5) ) )
D = np.asmatrix([ [4, 3], [2, 6] ])
F = np.eye(3, k=1) # tạo ma trận đường chéo. 3 là ma trận 3x3, k=1 là đường chéo nằm phía trên đường chéo chính (k = 0). 
print(A)
print(B)
print(C)
print(D)
print(F)

[[0.16771902 0.54181111]
 [0.84160253 0.13095604]]
[[1.+9.j 0.+2.j 0.+3.j]
 [0.+4.j 0.+5.j 0.+6.j]]
[[0.15676216 0.15058143 0.75996739 0.71450748 0.01534396]
 [0.94966854 0.77470828 0.43217144 0.20368248 0.54983419]
 [0.08000753 0.49253074 0.87786496 0.25478932 0.05010402]
 [0.05892352 0.59826367 0.64427997 0.61588085 0.89535855]
 [0.37542202 0.51483248 0.43834875 0.67838138 0.40524934]
 [0.97609086 0.05423416 0.9303297  0.05985192 0.91878085]
 [0.7341575  0.65265783 0.8518733  0.17815017 0.03786143]
 [0.5108343  0.57341781 0.83969025 0.22905101 0.53085168]
 [0.58658584 0.6276927  0.77916842 0.78868789 0.25668727]
 [0.66338469 0.85224629 0.78693251 0.73189434 0.94198746]]
[[4 3]
 [2 6]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]


In [15]:
F = np.eye(3, k=0)
print(F)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
F = np.eye(3, k=-1)
print(F)

[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


Các phép xử lý đơn giản


Xem hạng ma trận: 

In [19]:
np.linalg.matrix_rank(C)
print(C)

[[0.15676216 0.15058143 0.75996739 0.71450748 0.01534396]
 [0.94966854 0.77470828 0.43217144 0.20368248 0.54983419]
 [0.08000753 0.49253074 0.87786496 0.25478932 0.05010402]
 [0.05892352 0.59826367 0.64427997 0.61588085 0.89535855]
 [0.37542202 0.51483248 0.43834875 0.67838138 0.40524934]
 [0.97609086 0.05423416 0.9303297  0.05985192 0.91878085]
 [0.7341575  0.65265783 0.8518733  0.17815017 0.03786143]
 [0.5108343  0.57341781 0.83969025 0.22905101 0.53085168]
 [0.58658584 0.6276927  0.77916842 0.78868789 0.25668727]
 [0.66338469 0.85224629 0.78693251 0.73189434 0.94198746]]


In [20]:
A.I 

matrix([[-0.30172411,  1.24833854],
        [ 1.93906114, -0.38642639]])

In [21]:
linalg.inv(A)

array([[-0.30172411,  1.24833854],
       [ 1.93906114, -0.38642639]])

Định thức ma trận: 

In [23]:
linalg.det(A)

np.float64(-0.434025780892633)

Chuyển đổi ma trận:

In [24]:
A.T

matrix([[0.16771902, 0.84160253],
        [0.54181111, 0.13095604]])

In [25]:
A.H

matrix([[0.16771902, 0.84160253],
        [0.54181111, 0.13095604]])

Giải các loại phương trình tuyến tính: 

In [27]:
linalg.solve(A, b)

array([[-0.30172411 +2.27783715j,  0.         +5.63824449j,
         0.         +6.58485892j],
       [ 1.93906114+15.9058447j ,  0.         +1.94599031j,
         0.         +3.49862506j]])

In [36]:
E = np.asmatrix(a).T
print(E)

[[1]
 [2]
 [3]]


In [32]:
linalg.lstsq(F, E) 

(array([[2.],
        [3.],
        [0.]]),
 array([], dtype=float64),
 2,
 array([1., 1., 0.]))

Các hàm trên ma trận 

Giới thiệu một số hàm trên ma trận. Các bạn sinh viên thực tập trên ma trận A và D khai
báo bên trên: 

- Cộng ma trận:

In [33]:
np.add(A, D)

matrix([[4.16771902, 3.54181111],
        [2.84160253, 6.13095604]])

- Trừ ma trận: 

In [35]:
np.subtract(A, D) 

matrix([[-3.83228098, -2.45818889],
        [-1.15839747, -5.86904396]])

- Chia ma trận:

In [37]:
np.divide(A, D) 

matrix([[0.04192975, 0.1806037 ],
        [0.42080126, 0.02182601]])

- Nhân ma trận : 

In [38]:
A @ D 

matrix([[1.75449829, 3.75402372],
        [3.62832219, 3.31054384]])

In [39]:
np.multiply(D, A) 

matrix([[0.67087607, 1.62543333],
        [1.68320505, 0.78573626]])

In [40]:
np.dot(A, D)

matrix([[1.75449829, 3.75402372],
        [3.62832219, 3.31054384]])

In [41]:
np.vdot(A, D) 

matrix([[0.67087607]])

- Hàm lũy thừa và logarith ma trận: 

In [42]:
linalg.expm(A) 

array([[1.45920882, 0.67802564],
       [1.05318639, 1.41320342]])

In [43]:
linalg.logm(A) 

array([[-0.41120918+1.5280536j ,  0.1802892 -1.25988085j],
       [ 0.28004565-1.95698996j, -0.42344216+1.61353905j]])

2.3. Ma trận hội tụ 

Ma trận phân kỳ: 

In [44]:
import numpy as np

- Tính ma trận A: 

In [45]:
A = np.array([ [0,1], [1,0]])
print(A)

[[0 1]
 [1 0]]


In [46]:
temp = A.dot(A) # tính toan lần thứ 1
print(temp) 

[[1 0]
 [0 1]]


In [47]:
k= 6
for i in range(k-1):
    temp = temp.dot(A)
    print (temp)
    print('---') 

[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---
[[1 0]
 [0 1]]
---
[[0 1]
 [1 0]]
---


- Tính ma trận B:

In [48]:
B = np.array([ [0,-1], [-1,0]])
print(B) 

[[ 0 -1]
 [-1  0]]


In [49]:
temp = B.dot(B) # tính toan lần thứ 1
print(temp) 

[[1 0]
 [0 1]]


In [50]:
k= 5
for i in range(k-1):
    temp = temp.dot(B)
    print (temp)
    print('---')

[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---
[[ 0 -1]
 [-1  0]]
---
[[1 0]
 [0 1]]
---


- Ma trận hội tụ - Convergent matrix:  C=$\left(\begin{matrix}1 & 0 & 0\\0 & \frac{1}{2} & 1\\0 & 0 & \frac{1}{2}\end{matrix}\right) $

In [51]:
C = np.array([ [1, 0, 0], [0, 0.5, 1], [0, 0, 0.5] ])
print(C)

[[1.  0.  0. ]
 [0.  0.5 1. ]
 [0.  0.  0.5]]


In [52]:
temp = C.dot(C) # tính toan lần thứ 1
print(temp) 

[[1.   0.   0.  ]
 [0.   0.25 1.  ]
 [0.   0.   0.25]]


In [53]:
k= 1000
for i in range(k-1):
    temp = temp.dot(C)
print(temp) 

[[1.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 4.66631809e-302 9.34196882e-299]
 [0.00000000e+000 0.00000000e+000 4.66631809e-302]]


Sau đó, thực hiện thêm 1 lần tích 1000 lần nữa:

In [54]:
k= 1000
for i in range(k-1):
    temp = temp.dot(C)
print(temp) 

[[1. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


2.4. Ma trận Markov

In [55]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
MM = M.dot(M) # tính M2, nghĩa là M2
print (MM) 

[[0.7  0.45]
 [0.3  0.55]]


In [56]:
MM = M.dot(M) # tính M3
print (MM) 

[[0.7  0.45]
 [0.3  0.55]]


In [57]:
for i in range(100): # tính các M^ khác.
    MM = MM.dot(M)
print (MM) # kết luận xu hướng của jb

[[0.6 0.6]
 [0.4 0.4]]


3. Phương trình ma trận

3.2. Phân rã ma trận LU

In [59]:
M = np.array([ [0.8, 0.3], [0.2, 0.7]])
P, L, U = linalg.lu(M) 
print(P)
print(P)

[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [60]:
print(L)

[[1.   0.  ]
 [0.25 1.  ]]


In [61]:
print(U)

[[0.8   0.3  ]
 [0.    0.625]]


Thử lại với phép nhân LU có bằng ma trận M ban đầu hay không: 

In [62]:
L.dot(U) 

array([[0.8, 0.3],
       [0.2, 0.7]])

5. Bài toán ứng dụng 2 – Bài toán loan tin

In [63]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
temp = A.dot(A) 
print(temp) 

[[1 1 1 0]
 [1 0 0 1]
 [1 2 0 1]
 [0 1 1 1]]


In [64]:
temp = temp.dot(A)
print(temp) 

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]


In [65]:
A = np.array([ [0,1,0,1],[0,0,1,0],[1,0,0,1],[1,1,0,0]])
sumA = A
temp = A.dot(A)
k = 3
sumA = sumA + temp
for i in range(1, k-1):
    temp = temp.dot(A)
    sumA = sumA + temp
print (temp)
print (sumA) 

[[1 1 1 2]
 [1 2 0 1]
 [1 2 2 1]
 [2 1 1 1]]
[[2 3 2 3]
 [2 2 1 2]
 [3 4 2 3]
 [3 3 2 2]]


Bài Tập Chương 3 

Câu 1 : Hãy viết chương trình bằng Python hoặc sử dụng thư viện numpy/sympy để:

a. Tự chọn một ma trận khả nghịch 3x3. Sinh viên chứng minh ma trận đó khả nghịch (tồn tại ma trận nghịch đảo) 

In [66]:
import numpy as np
from scipy import linalg

A=np.array([[2, -1, 0],
            [1, 3, 1],
            [1, -1, 2]])
det_A=np.linalg.det(A)
print("Định thức của A:",det_A)
if det_A != 0:
    print("Ma trận khả nghịch")
    A_inv = np.linalg.inv(A)
    print("Ma trận nghịch đảo của A:\n",A_inv)
else:
    print("Ma trận không khả nghịch")

Định thức của A: 15.0
Ma trận khả nghịch
Ma trận nghịch đảo của A:
 [[ 0.46666667  0.13333333 -0.06666667]
 [-0.06666667  0.26666667 -0.13333333]
 [-0.26666667  0.06666667  0.46666667]]


b. Nhập họ và tên hoặc mã số sinh viên (của sinh viên)

In [ ]:
ma_sv=input("Nhập họ tên hoặc mã số sinh viên: ")

c. Mã hóa họ và tên hoặc mã số sinh viên (của sinh viên). 

In [ ]:
mahoa=' '.join(str(ord(c)) for c in ma_sv)
print("Mã hoá:",mahoa)

d. Thực hiện giải mã với ma trận được chọn.

In [ ]:
chuoima=input("Nhập chuỗi mã hoá (các số cách nhau bằng cách cách): ")
danhsachso=list(map(int,chuoima.split()))
chuoigiaima = ''.join(chr(i) for i in danhsachso)
print("Thông điệp giải mã:",chuoigiaima)

Câu 2: Tính toán phân số từ liên phân số (continued fractions)

a.Viết chương trình tính 
𝑝
𝑛
p 
n
​
  và 
𝑞
𝑛
q 
n
​
  từ danh sách các hệ số 
𝑐
0
,
𝑐
1
,
.
.
.
,
𝑐
𝑛
c 
0
​
 ,c 
1
​
 ,...,c 
n
​
 .
 

In [67]:
import numpy as np
def continued_fraction(c):
    vec=np.array([[1], [0]])
    for ci in reversed(c):
        mat=np.array([[ci, 1],
                      [1,  0]])
        vec=mat @ vec
    return vec[0, 0], vec[1, 0]
coeffs=[2, 1, 2]
pn,qn=continued_fraction(coeffs)
print(f"p_n ={pn} \n q_n={qn} \n phân số={pn}/{qn}={pn/qn}")

p_n =8 
 q_n=3 
 phân số=8/3=2.6666666666666665


b.Chứng minh công thức truy hồi ma trận:

In [68]:
import numpy as np
def compute_fraction_matrix(c_list):
    vec=np.array([[1], [0]])  
    for ci in reversed(c_list): 
        M=np.array([[ci, 1], [1, 0]])
        vec=M @ vec
    return int(vec[0, 0]), int(vec[1, 0])
def verify_by_recurrence(c_list):
    p_prev, p_curr=1, c_list[0]
    q_prev, q_curr=0, 1
    for i in range(1, len(c_list)):
        p_next=c_list[i]*p_curr+p_prev
        q_next=c_list[i]*q_curr+q_prev
        p_prev,p_curr=p_curr,p_next
        q_prev,q_curr=q_curr,q_next
    return p_curr,q_curr
c=[2,1,2]  
pn_mat,qn_mat=compute_fraction_matrix(c)
pn_rec,qn_rec=verify_by_recurrence(c)
print(f"Theo nhân ma trận: p_n={pn_mat} \n q_n={qn_mat} \n p_n/q_n={pn_mat/qn_mat}")
print(f"Theo truy hồi:     p_n={pn_rec} \n q_n={qn_rec} \n p_n/q_n={pn_rec/qn_rec}")

Theo nhân ma trận: p_n=8 
 q_n=3 
 p_n/q_n=2.6666666666666665
Theo truy hồi:     p_n=8 
 q_n=3 
 p_n/q_n=2.6666666666666665
