câu 1

In [1]:
import numpy as np

A = np.array([2, -1, 3, 0])
B = np.array([1, 4, -2, 5])

tong = A + B
hieu = 3*A - 2*B

print("a) A + B =", tong)
print("a) 3A - 2B =", hieu)

dot_product = np.dot(A, B)
normA = np.linalg.norm(A)
normB = np.linalg.norm(B)
cos_theta = dot_product / (normA * normB)
angle_deg = np.degrees(np.arccos(cos_theta))

print("b) Tích vô hướng A · B =", dot_product)
print("b) Góc giữa A và B (độ) =", round(angle_deg, 3))

C = np.array([[1, 2, -1],
              [0, 3, 4],
              [2, -1, 0]])

CT = C.T
CTC = CT @ C

print("c) C^T * C =\n", CTC)


a) A + B = [3 3 1 5]
a) 3A - 2B = [  4 -11  13 -10]
b) Tích vô hướng A · B = -8
b) Góc giữa A và B (độ) = 108.376
c) C^T * C =
 [[ 5  0 -1]
 [ 0 14 10]
 [-1 10 17]]


câu 2

In [2]:
import numpy as np

M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9],
              [0, 1, 1]])

N = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])

print("a) M · N =\n", M @ N)

try:
    det_M = np.linalg.det(M)
    print("b) Định thức của M =", det_M)
except:
    print("b) Không tính được định thức của M (ma trận không vuông)")

rank_M = np.linalg.matrix_rank(M)
print("c) Hạng của M =", rank_M)


a) M · N =
 [[ 32  38  44  50]
 [ 68  83  98 113]
 [104 128 152 176]
 [ 12  14  16  18]]
b) Không tính được định thức của M (ma trận không vuông)
c) Hạng của M = 3


câu 3

In [3]:
P = np.array([[2, 1, 0, -1],
              [0, 3, 1, -1],
              [1, 0, 4, 2],
              [0, 1, 0, 3]])

b3 = np.array([4, 7, 9, 5])

try:
    P_inv = np.linalg.inv(P)
    print("a) Ma trận nghịch đảo P^-1 =\n", P_inv)
except:
    print("a) P không khả nghịch")

x3 = np.linalg.solve(P, b3)
print("b) Nghiệm của hệ P · x = b là:", x3)

check = P @ x3
print("c) Kiểm tra lại: P · x =", check)
print("   So sánh với b =", b3)


a) Ma trận nghịch đảo P^-1 =
 [[ 0.47727273 -0.18181818  0.04545455  0.06818182]
 [ 0.03409091  0.27272727 -0.06818182  0.14772727]
 [-0.11363636  0.09090909  0.22727273 -0.15909091]
 [-0.01136364 -0.09090909  0.02272727  0.28409091]]
b) Nghiệm của hệ P · x = b là: [1.38636364 2.17045455 1.43181818 0.94318182]
c) Kiểm tra lại: P · x = [4. 7. 9. 5.]
   So sánh với b = [4 7 9 5]


câu 4

In [4]:
Q = np.array([[4, -1, 0],
              [1, 3, -2],
              [0, 1, 2]])

eigvals, eigvecs = np.linalg.eig(Q)
print("a) Giá trị riêng:", eigvals)
print("b) Vector riêng:\n", eigvecs)

eigvecs_norm = eigvecs / np.linalg.norm(eigvecs, axis=0)
print("c) Vector riêng chuẩn hóa (chuẩn 1):\n", eigvecs_norm)


a) Giá trị riêng: [3.45339765+0.j         2.77330117+1.46771151j 2.77330117-1.46771151j]
b) Vector riêng:
 [[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743-0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]
c) Vector riêng chuẩn hóa (chuẩn 1):
 [[ 0.83327121+0.j         -0.26206044-0.31354813j -0.26206044+0.31354813j]
 [ 0.455468  +0.j         -0.78166743+0.j         -0.78166743+0.j        ]
 [ 0.31338154+0.j         -0.21963176+0.41685708j -0.21963176-0.41685708j]]


câu 5

In [5]:
R = np.array([[1, -2, 3],
              [2, 0, 1],
              [-1, 1, 4]])
b5 = np.array([10, 8, 7])

x5 = np.linalg.solve(R, b5)
print("a) Nghiệm x của hệ Rx = b:", x5)

det_R = np.linalg.det(R)
print("b) Định thức của R =", det_R)

if det_R != 0:
    R_inv = np.linalg.inv(R)
    x_check = R_inv @ b5
    print("   R khả nghịch. Nghiệm kiểm lại bằng R^-1:", x_check)
else:
    print("   R không khả nghịch.")

frobenius = np.linalg.norm(R, ord='fro')
print("c) Chuẩn Frobenius của R =", frobenius)


a) Nghiệm x của hệ Rx = b: [2.7826087  0.04347826 2.43478261]
b) Định thức của R = 23.0
   R khả nghịch. Nghiệm kiểm lại bằng R^-1: [2.7826087  0.04347826 2.43478261]
c) Chuẩn Frobenius của R = 6.082762530298219
