câu 1

In [2]:
import numpy as np

A = np.array([-2, 1, 4])
B = np.array([-1, 5, 0])
C = np.array([[2, -1, 3],
              [1, 4, -2],
              [0, 2, 5]])

tong_AB = A + B
tich_2A_3B = 2 * A + 3 * B
print("Tổng vector A + B:", tong_AB)
print("Tích số 2A + 3B:", tich_2A_3B)

tich_vo_huong = np.dot(A, B)
goc = np.arccos(tich_vo_huong / (np.linalg.norm(A) * np.linalg.norm(B))) * 180 / np.pi
print("Tích vô hướng A và B:", tich_vo_huong)
print("Góc giữa A và B (độ):", goc)

C_transpose = C.T
tich_CCt = np.dot(C, C_transpose)
print("Tích ma trận C * C^T:\n", tich_CCt)

Tổng vector A + B: [-3  6  4]
Tích số 2A + 3B: [-7 17  8]
Tích vô hướng A và B: 7
Góc giữa A và B (độ): 72.56808102284828
Tích ma trận C * C^T:
 [[14 -8 13]
 [-8 21 -2]
 [13 -2 29]]


câu 2

In [3]:
import numpy as np

M = np.array([[2, -1, 3, 0],
              [1, 4, -2, 5],
              [0, 2, 6, -3],
              [-1, 0, 1, 4]])

N = np.array([[1, 3, -2, 0],
              [4, -1, 5, 2],
              [0, 2, 3, -1],
              [-3, 1, 0, 4]])

tich_MN = np.dot(M, N)
print("Tích ma trận M x N:\n", tich_MN)

det_M = np.linalg.det(M)
print("Định thức của ma trận M:", det_M)

hang_N = np.linalg.matrix_rank(N)
print("Hạng của ma trận N:", hang_N)

Tích ma trận M x N:
 [[ -2  13   0  -5]
 [  2   0  12  30]
 [ 17   7  28 -14]
 [-13   3   5  15]]
Định thức của ma trận M: 409.00000000000017
Hạng của ma trận N: 4


câu 3

In [4]:
import numpy as np

P = np.array([[3, -1, 0, 2],
              [1, 4, -2, 0],
              [0, 1, 5, -1],
              [2, 0, 1, 3]])

b = np.array([6, 8, 3, 7])

P_inv = np.linalg.inv(P)
print("Ma trận nghịch đảo của P:\n", P_inv)

x = np.linalg.solve(P, b)
print("Nghiệm của hệ phương trình [x, y, z, w]:", x)

kiem_tra = np.dot(P, x)
print("Kiểm tra P * x:\n", kiem_tra)
print("Vector hạng số b:", b)

Ma trận nghịch đảo của P:
 [[ 0.5         0.1         0.1        -0.3       ]
 [-0.14285714  0.2         0.05714286  0.11428571]
 [-0.03571429 -0.05        0.16428571  0.07857143]
 [-0.32142857 -0.05       -0.12142857  0.50714286]]
Nghiệm của hệ phương trình [x, y, z, w]: [2.         1.71428571 0.42857143 0.85714286]
Kiểm tra P * x:
 [6. 8. 3. 7.]
Vector hạng số b: [6 8 3 7]


câu 4

In [5]:
import numpy as np

Q = np.array([[5, -2, 1],
              [0, 3, -1],
              [2, 0, 4]])

gia_tri_rieng, vector_rieng = np.linalg.eig(Q)
print("Các giá trị riêng của ma trận Q:", gia_tri_rieng)

print("Các vector riêng tương ứng:\n", vector_rieng)

for i in range(vector_rieng.shape[1]):
    v = vector_rieng[:, i]
    chuan_hoa = v / np.linalg.norm(v)
    print(f"Vector riêng chuẩn hóa {i+1}:", chuan_hoa)

Các giá trị riêng của ma trận Q: [6.3553014+0.j         2.8223493+1.07730381j 2.8223493-1.07730381j]
Các vector riêng tương ứng:
 [[ 0.74846013+0.j         -0.37423006+0.34234215j -0.37423006-0.34234215j]
 [-0.18941773+0.j          0.09470887+0.57433055j  0.09470887-0.57433055j]
 [ 0.63555359+0.j          0.63555359+0.j          0.63555359-0.j        ]]
Vector riêng chuẩn hóa 1: [ 0.74846013+0.j -0.18941773+0.j  0.63555359+0.j]
Vector riêng chuẩn hóa 2: [-0.37423006+0.34234215j  0.09470887+0.57433055j  0.63555359+0.j        ]
Vector riêng chuẩn hóa 3: [-0.37423006-0.34234215j  0.09470887-0.57433055j  0.63555359-0.j        ]


câu 5

In [6]:
import numpy as np

R = np.array([[4, -1, 2],
              [1, 3, -2],
              [0, 2, 5]])

b = np.array([12, 5, 9])

x = np.linalg.solve(R, b)
print("Nghiệm của hệ phương trình R * x = b:", x)

det_R = np.linalg.det(R)
if abs(det_R) < 1e-10:
    print("Ma trận R không khả nghịch vì định thức gần 0.")
else:
    R_inv = np.linalg.inv(R)
    x_inv = np.dot(R_inv, b)
    print("Ma trận nghịch đảo của R:\n", R_inv)
    print("Nghiệm từ ma trận nghịch đảo:", x_inv)

chuẩn_frobenius = np.sqrt(np.sum(R ** 2))
print("Chuẩn Frobenius của ma trận R:", chuẩn_frobenius)

Nghiệm của hệ phương trình R * x = b: [2.78823529 1.52941176 1.18823529]
Ma trận nghịch đảo của R:
 [[ 0.22352941  0.10588235 -0.04705882]
 [-0.05882353  0.23529412  0.11764706]
 [ 0.02352941 -0.09411765  0.15294118]]
Nghiệm từ ma trận nghịch đảo: [2.78823529 1.52941176 1.18823529]
Chuẩn Frobenius của ma trận R: 8.0
