In [ ]:
#1.1

In [1]:
import numpy as np
D = np.array([[1, 2], [3, 4]])
try:
    np.copyto(E, D)
except Exception as e1:
    print("Lỗi khi chưa khởi tạo E:", e1)
E = np.array([[1, 2], [3, 5]])
np.copyto(E, D)
print("Ma trận E sau khi copy từ D:\n", E)


Lỗi khi chưa khởi tạo E: name 'E' is not defined
Ma trận E sau khi copy từ D:
 [[1 2]
 [3 4]]


In [3]:
B = np.matrix("[1 2 3; 4 5 6]")  
print("Ma trận B tạo từ chuỗi:\n", B)

x = np.array([['a', 'b'], ['c', 'd']])
y = 'x'
try:
    C = np.matrix([[x, y], [1, 2]])
    print(" Ma trận C:\n", C)
except Exception as e:
    print("Lỗi khi tạo matrix C chứa đối tượng hỗn hợp:", e)


Ma trận B tạo từ chuỗi:
 [[1 2 3]
 [4 5 6]]
Lỗi khi tạo matrix C chứa đối tượng hỗn hợp: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.


In [ ]:
#1.2

In [4]:
try:
    A_matrix = np.matrix([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
except Exception as e2:
    print("Lỗi khi tạo matrix 3D:", e2)

A_array = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Array 3D:\n", A_array)


Lỗi khi tạo matrix 3D: matrix must be 2-dimensional
Array 3D:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [6]:
B = np.matrix("[1 2 3; 4 5 6]")  
print(" Ma trận B tạo từ chuỗi:\n", B)

x = np.array([['a', 'b'], ['c', 'd']])
y = 'x'
try:
    C = np.matrix([[x, y], [1, 2]])
    print(" Ma trận C:\n", C)
except Exception as e:
    print(" Lỗi khi tạo matrix C chứa đối tượng hỗn hợp:", e)


 Ma trận B tạo từ chuỗi:
 [[1 2 3]
 [4 5 6]]
 Lỗi khi tạo matrix C chứa đối tượng hỗn hợp: setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (2, 2) + inhomogeneous part.
