In [2]:
import numpy as np

#1 Khởi tạo mảng M1
M1= np.array([9, 12, 23, 30])
print("Mảng M1:", M1)
#Kết quả: Mảng M1: [ 9 12 23 30]

#2 Nhân vector u và mảng M1
u = np.array([2, 1])
#Tính tích vô hướng của M1 và u
#Chỉ dùng phần tử đầu của M1 để phù hợp với u (2 phần tử)
tichM1u= M1[:2].dot(u)
print("Tích M1[:2] và u (M1[:2].u):", tichM1u)
#Kết quả: 9*2 + 12*1= 18 + 12= 30

#3 Nhân ngược của u và phần tử đầu của M1 (hoặc cũng có thể xem như nhân 2 vector)
tichhuM1= u.dot(M1[:2])
print("Tích u và M1[:2] (u.M1[:2]):", tichhuM1)
# Kết quả: 30

#4 Tạo các mảng để thao tác
mat1= np.zeros([5, 5])#Mảng 5x5 toàn 0
print("mat1:\n", mat1)
#Kết quả:
# [[0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]
#  [0. 0. 0. 0. 0.]]

mat2 = np.ones([5, 5])#Mảng 5x5 toàn 1
print("mat2:\n", mat2)
#Kết quả:
# [[1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]
#  [1. 1. 1. 1. 1.]]

#Tính phần tử mới bằng phép cộng và nhân
mat3= mat1 + 2 * mat2
print("mat3= mat1 + 2 * mat2:\n", mat3)
#Kết quả:
# [[2. 2. 2. 2. 2.]
#  [2. 2. 2. 2. 2.]
#  [2. 2. 2. 2. 2.]
#  [2. 2. 2. 2. 2.]
#  [2. 2. 2. 2. 2.]]

#Sao chép mảng
mat4= np.copy(mat3)
print("mat4 (sao chép của mat3):\n", mat4)
#Kết quả giống mat3:
# [[2. 2. 2. 2. 2.]
#  [2. 2. 2. 2. 2.]
#  [2. 2. 2. 2. 2.]
#  [2. 2. 2. 2. 2.]
#  [2. 2. 2. 2. 2.]]

#Kiểm tra phần tử cụ thể
element = mat3[3, 2]
print("Phần tử tại hàng 3, cột 2 của mat3:", element)
#Kết quả: 2.0

#5 Thao tác với mảng ngẫu nhiên
mat8 = np.random.random([4, 5])
print("mat8 (mảng ngẫu nhiên 4x5):\n", mat8)
#Kết quả: mảng 4x5 ngẫu nhiên, ví dụ:
# [[0.423 0.567 0.783 0.245 0.512]
#  [0.234 0.789 0.123 0.456 0.678]
#  [0.987 0.654 0.321 0.876 0.543]
#  [0.135 0.246 0.357 0.468 0.579]]

#Kiểm tra ma trận identity
identity_matrix= np.identity(4)
print("Ma trận đơn vị 4x4:\n", identity_matrix)
#Kết quả:
# [[1. 0. 0. 0.]
#  [0. 1. 0. 0.]
#  [0. 0. 1. 0.]
#  [0. 0. 0. 1.]]

#Kiểm tra bằng np.allclose
print("mat3 và mat4 có giống nhau không?", np.allclose(mat3, mat4))
#Kết quả: True

#Các phép kiểm tra và thao tác
print("Kích thước của mat3:", mat3.shape)
#Kết quả: (5, 5)

print("Kiểu dữ liệu của mat3:", mat3.dtype)
#Kết quả: float64 (hoặc tương tự tùy hệ thống)

# Kiểm tra xem mảng có rỗng không (chưa chính xác, sửa lại)
print("Mat3 có rỗng không:", mat3.size== 0)
#Kết quả: False

#Thay đổi phần tử trong mảng
mat3[1, 1] = 99
print("Sau khi thay đổi phần tử [1,1]:\n", mat3)
# Kết quả:
# [[ 2.  2.  2.  2.  2.]
#  [ 2. 99.  2.  2.  2.]
#  [ 2.  2.  2.  2.  2.]
#  [ 2.  2.  2.  2.  2.]
#  [ 2.  2.  2.  2.  2.]]

Mảng M1: [ 9 12 23 30]
Tích M1[:2] và u (M1[:2].u): 30
Tích u và M1[:2] (u.M1[:2]): 30
mat1:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
mat2:
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
mat3= mat1 + 2 * mat2:
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
mat4 (sao chép của mat3):
 [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]
Phần tử tại hàng 3, cột 2 của mat3: 2.0
mat8 (mảng ngẫu nhiên 4x5):
 [[0.07546254 0.71982047 0.68318078 0.53887287 0.60609838]
 [0.80746664 0.09912252 0.9157572  0.42607266 0.27325367]
 [0.44405745 0.70702115 0.01702638 0.17336427 0.26688407]
 [0.67244034 0.90381132 0.81337744 0.71633234 0.98090768]]
Ma trận đơn vị 4x4:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
mat3 và mat4 có giống nhau không? True
Kích thước của mat3: (5, 5)
Kiểu dữ liệu của mat3: float64
Ma